### ISSUE TITLE
Required new props in config

### ISSUE THREAD

**Issue by Romaixn** [rompetomp/inertia-bundle#43]
Hello, with the last update (2.3.1) It's required to have that is a config file : 

```
rompetomp_inertia:
  ssr:
    enabled: false
    url: 'http://127.0.0.1:13714/render'

```

Otherwise it throws an error.  Maybe do a check to make it optional? Or add it in a recipe.
